/**
 * Copyright 2015-2020 OpenCB
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * WARNING: AUTOGENERATED CODE
 * 
 * This code was generated by a tool.
 * Autogenerated on: 2020-03-23 15:40:59
 * 
 * Manual changes to this file may cause unexpected behavior in your application.
 * Manual changes to this file will be overwritten if the code is regenerated. 
 *
**/

import OpenCGAParentClass from "../opencga-parent-class.js";


/**
 * This class contains the methods for the "Admin" resource
 */

export default class Admin extends OpenCGAParentClass {

    constructor(config) {
        super(config);
    }

    /** Group by operation
    * @param {String} fields - Comma separated list of fields by which to group by.
    * @param {String} entity - Entity to be grouped by.
    * @param {Object} [params] - The Object containing the following optional parameters:
    * @param {Boolean} [params.count] - Count the number of elements matching the group.
    * @param {Number} [params.limit = "50"] - Maximum number of documents (groups) to be returned. The default value is 50.
    * @param {String} [params.action] - Action performed.
    * @param {String} [params.before] - Object before update.
    * @param {String} [params.after] - Object after update.
    * @param {String} [params.date] - Date <,<=,>,>=(Format: yyyyMMddHHmmss) and yyyyMMddHHmmss-yyyyMMddHHmmss.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    groupByAudit(fields, entity, params) {
        return this._get("admin", null, "audit", null, "groupBy", {fields, entity, ...params});
    }

    /** Sync Catalog into the Solr
    * 
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    indexStatsCatalog() {
        return this._post("admin", null, "catalog", null, "indexStats");
    }

    /** Install OpenCGA database
    * @param {Object} data - JSON containing the mandatory parameters.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    installCatalog(data) {
        return this._post("admin", null, "catalog", null, "install", data);
    }

    /** Change JWT secret key
    * @param {Object} data - JSON containing the parameters.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    jwtCatalog(data) {
        return this._post("admin", null, "catalog", null, "jwt", data);
    }

    /** Handle global panels
    * @param {Object} [data] - Panel parameters to be installed.
    * @param {Object} [params] - The Object containing the following optional parameters:
    * @param {Boolean} [params.panelApp = "false"] - Import panels from PanelApp (GEL). The default value is false.
    * @param {Boolean} [params.overwrite = "false"] - Flag indicating to overwrite installed panels in case of an ID conflict. The default
    *     value is false.
    * @param {String} [params.delete] - Comma separated list of global panel ids to delete.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    panelCatalog(data, params) {
        return this._post("admin", null, "catalog", null, "panel", data, params);
    }

    /** Create a new user
    * @param {Object} data - JSON containing the parameters.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    createUsers(data) {
        return this._post("admin", null, "users", null, "create", data);
    }

    /** Import users or a group of users from LDAP or AAD
    * @param {Object} data - JSON containing the parameters.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    importUsers(data) {
        return this._post("admin", null, "users", null, "import", data);
    }

    /** Synchronise groups of users with LDAP groups
    * @param {Object} data - JSON containing the parameters.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    syncUsers(data) {
        return this._post("admin", null, "users", null, "sync", data);
    }

}