/**
 * Copyright 2015-2020 OpenCB
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * WARNING: AUTOGENERATED CODE
 * 
 * This code was generated by a tool.
 * Autogenerated on: 2020-03-23 15:40:58
 * 
 * Manual changes to this file may cause unexpected behavior in your application.
 * Manual changes to this file will be overwritten if the code is regenerated. 
 *
**/

import OpenCGAParentClass from "../opencga-parent-class.js";


/**
 * This class contains the methods for the "Job" resource
 */

export default class Job extends OpenCGAParentClass {

    constructor(config) {
        super(config);
    }

    /** Update the set of permissions granted for the member
    * @param {String} members - Comma separated list of user or group ids.
    * @param {Object} data - JSON containing the parameters to add ACLs.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    updateAcl(members, data) {
        return this._post("jobs", members, null, null, "update", data);
    }

    /** Register an executed job with POST method
    * @param {Object} data - job.
    * @param {Object} [params] - The Object containing the following optional parameters:
    * @param {String} [params.study] - Study [[user@]project:]study where study and project can be either the ID or UUID.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    create(data, params) {
        return this._post("jobs", null, null, null, "create", data, params);
    }

    /** Job search method
    * @param {Object} [params] - The Object containing the following optional parameters:
    * @param {String} [params.include] - Fields included in the response, whole JSON path must be provided.
    * @param {String} [params.exclude] - Fields excluded in the response, whole JSON path must be provided.
    * @param {Number} [params.limit] - Number of results to be returned.
    * @param {Number} [params.skip] - Number of results to skip.
    * @param {Boolean} [params.count = "false"] - Get the total number of results matching the query. Deactivated by default. The default
    *     value is false.
    * @param {String} [params.study] - Study [[user@]project:]study where study and project can be either the ID or UUID.
    * @param {Boolean} [params.otherStudies = "false"] - Flag indicating the entries being queried can belong to any related study, not just
    *     the primary one. The default value is false.
    * @param {String} [params.id] - Job ID. It must be a unique string within the study. An id will be autogenerated automatically if not
    *     provided.
    * @param {String} [params.tool] - Tool executed by the job.
    * @param {String} [params.user] - User that created the job.
    * @param {String} [params.priority] - Priority of the job.
    * @param {String} [params.internal.status.name] - Job internal status.
    * @param {String} [params.creationDate] - Creation date. Format: yyyyMMddHHmmss. Examples: >2018, 2017-2018, <201805.
    * @param {String} [params.modificationDate] - Modification date. Format: yyyyMMddHHmmss. Examples: >2018, 2017-2018, <201805.
    * @param {Boolean} [params.visited] - Visited status of job.
    * @param {String} [params.tags] - Job tags.
    * @param {String} [params.input] - Comma separated list of file ids used as input.
    * @param {String} [params.output] - Comma separated list of file ids used as output.
    * @param {String} [params.acl] - Filter entries for which a user has the provided permissions. Format: acl={user}:{permissions}.
    *     Example: acl=john:WRITE,WRITE_ANNOTATIONS will return all entries for which user john has both WRITE and WRITE_ANNOTATIONS
    *     permissions. Only study owners or administrators can query by this field. .
    * @param {String} [params.release] - Release when it was created.
    * @param {Boolean} [params.deleted = "false"] - Boolean to retrieve deleted jobs. The default value is false.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    search(params) {
        return this._get("jobs", null, null, null, "search", params);
    }

    /** Return the acl of the job. If member is provided, it will only return the acl for the member.
    * @param {String} jobs - Comma separated list of job IDs or UUIDs up to a maximum of 100.
    * @param {Object} [params] - The Object containing the following optional parameters:
    * @param {String} [params.member] - User or group id.
    * @param {Boolean} [params.silent = "false"] - Boolean to retrieve all possible entries that are queried for, false to raise an
    *     exception whenever one of the entries looked for cannot be shown for whichever reason. The default value is false.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    acl(jobs, params) {
        return this._get("jobs", jobs, null, null, "acl", params);
    }

    /** Delete existing jobs
    * @param {String} [jobs] - Comma separated list of job ids.
    * @param {Object} [params] - The Object containing the following optional parameters:
    * @param {String} [params.study] - Study [[user@]project:]study where study and project can be either the ID or UUID.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    delete(jobs, params) {
        return this._delete("jobs", jobs, null, null, "delete", params);
    }

    /** Get job information
    * @param {String} jobs - Comma separated list of job IDs or UUIDs up to a maximum of 100.
    * @param {Object} [params] - The Object containing the following optional parameters:
    * @param {String} [params.include] - Fields included in the response, whole JSON path must be provided.
    * @param {String} [params.exclude] - Fields excluded in the response, whole JSON path must be provided.
    * @param {String} [params.study] - Study [[user@]project:]study where study and project can be either the ID or UUID.
    * @param {Boolean} [params.deleted = "false"] - Boolean to retrieve deleted jobs. The default value is false.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    info(jobs, params) {
        return this._get("jobs", jobs, null, null, "info", params);
    }

    /** Update some job attributes
    * @param {String} jobs - Comma separated list of job IDs or UUIDs up to a maximum of 100.
    * @param {Object} [data] - params.
    * @param {Object} [params] - The Object containing the following optional parameters:
    * @param {String} [params.study] - Study [[user@]project:]study where study and project can be either the ID or UUID.
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    update(jobs, data, params) {
        return this._post("jobs", jobs, null, null, "update", data, params);
    }

    /** Show the first lines of a log file (up to a limit)
    * @param {String} job - Job ID or UUID.
    * @param {Object} [params] - The Object containing the following optional parameters:
    * @param {String} [params.study] - Study [[user@]project:]study where study and project can be either the ID or UUID.
    * @param {Number} [params.offset] - Starting byte from which the file will be read.
    * @param {Number} [params.lines] - Maximum number of lines to be returned.
    * @param {String} [params.type] - Log file to be shown (stdout or stderr).
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    headLog(job, params) {
        return this._get("jobs", job, "log", null, "head", params);
    }

    /** Show the last lines of a log file (up to a limit)
    * @param {String} job - Job ID or UUID.
    * @param {Object} [params] - The Object containing the following optional parameters:
    * @param {String} [params.study] - Study [[user@]project:]study where study and project can be either the ID or UUID.
    * @param {Number} [params.lines] - Maximum number of lines to be returned.
    * @param {String} [params.type] - Log file to be shown (stdout or stderr).
    * @returns {Promise} Promise object in the form of RestResponse instance.
    */
    tailLog(job, params) {
        return this._get("jobs", job, "log", null, "tail", params);
    }

}