name: "Reusable workflow to publish JSorolla in DockerHub"

on:
  workflow_call:
    inputs:
      docker_tag:
        type: string
        required: false
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
      DOCKER_HUB_ORGANISATION:
        required: true
      DOCKER_IMAGES_JSOROLLA:
        required: true
      JSOROLLA_CUSTOM_SITES_REPOSITORY:
        required: true
      GH_PRIVATE_TOKEN:
        required: true

jobs:
  docker-jsorolla-workflow:
    name: Publish JSorolla Docker
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout JSorolla"
        uses: actions/checkout@v2
      - name: "Checkout private custom sites repo inside JSorolla"
        uses: actions/checkout@v2
        if: ${{ github.repository != 'opencb/jsorolla' }}
        with:
          token: ${{ secrets.GH_PRIVATE_TOKEN }}
          repository: ${{ secrets.JSOROLLA_CUSTOM_SITES_REPOSITORY }}
          ref: main
          path: custom-sites
      - uses: actions/download-artifact@v2
        with:
          name: jsorolla-build
          path: build
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - run: python3 ./docker/docker-build.py push --organisation ${{ secrets.DOCKER_HUB_ORGANISATION }} --images ${{ secrets.DOCKER_IMAGES_JSOROLLA }} --tag ${{ inputs.docker_tag }}
