name: "Release"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: opencb/jsorolla/.github/workflows/build-jsorolla-workflow.yml@develop

  docker:
    needs: build
    uses: opencb/jsorolla/.github/workflows/docker-jsorolla-workflow.yml@develop
    with:
      docker_tag: ${{ needs.build.outputs.version }}
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_ORGANISATION: ${{ secrets.DOCKER_HUB_ORGANISATION }}
      DOCKER_IMAGES_JSOROLLA: ${{ secrets.DOCKER_IMAGES_JSOROLLA }}
      JSOROLLA_CUSTOM_SITES_REPOSITORY: ${{ secrets.JSOROLLA_CUSTOM_SITES_REPOSITORY }}
      GH_PRIVATE_TOKEN: ${{ secrets.GH_PRIVATE_TOKEN }}

  release:
    needs: [build, docker]
    uses: opencb/java-common-libs/.github/workflows/release-github-workflow.yml@develop
    with:
      artifact: jsorolla-release
      file: iva-${{ needs.build.outputs.version }}.tar.gz

  deploy:
    needs: build
#    if: ${{ github.repository == "opencb/jsorolla" }}
    uses: opencb/jsorolla/.github/workflows/deploy-jsorolla-workflow.yml@develop
    with:
      version: ${{ needs.build.outputs.version }}
    secrets:
      SSH_SWDEV_IP: ${{ secrets.SSH_SWDEV_IP }}
      SSH_SWDEV_USER: ${{ secrets.SSH_SWDEV_USER }}
      SSH_SWDEV_PASSWORD: ${{ secrets.SSH_SWDEV_PASSWORD }}
