name: "Build and Run tests"

on:
  workflow_call:
    inputs:
      test_profile:
        type: string
        required: true
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  test:
    name: "Test and push Sonar analysis"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "package.json"
      - run: npm install
      - uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: build
      - run: npm run test:prepare
      - uses: cypress-io/github-action@v5
        with:
          start: npm run serve:build
          command: npm run test:run
          browser: chrome
          wait-on: 'http://localhost:4000/test-app/'
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-report
          path: |
            cypress/reports/assets
            cypress/reports/*.html
            cypress/screenshots
            cypress/videos
